
name: NAFNet_w32_k935_u3

model:
  # load_path: ./pretrained_models/NAFNet_w16_u111.pth
  save_path: ./pretrained_models/
  device: 'cuda'

  network_arch:
    type: NAFNet
    width: 32
    enc_blk_nums: []
    mid_blk_num: 3
    dec_blk_nums: []

    intro_k: 9
    ending_k: 5

    block:
      dw_expand: 2
      ffn_expand: 2
      kernel_size: 3

training:
  iterations: 12000
  valid_interval: 100
  batch_size: 32

  optimizer:
    type: AdamW
    weight_decay: 0.0
    lr: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingLR
    t_max: 12000
    eta_min: !!float 1e-7

  losses:
    mseloss:
      weight: 1.0
    l1loss:
      weight: 0.01

datasets:
  training:
    data_path: ~/Downloads/DIV2K_train_HR/
    
  validation:  
    data_path: ~/Downloads/DIV2K_valid_HR/

  patch_size: 256
  workers: 6


