
name: Deep-SRNAFNet_Test

model:
  # load_path: ./pretrained_models/Deep-SRNAFNet_V3.pth
  save_path: ./pretrained_models/
  device: 'cuda'

  network_arch:
    type: SRNAFNet
    width: 32
    enc_blk_nums: []
    mid_blk_num: 1
    dec_blk_nums: []

    intro_k: 3
    ending_k: 3

    sfe_k_nums: [3, 5, 7]
    dfe_count: 1
    dfe_k: 3
    ufe_count: 1
    ufe_k: 3

    block:
      dw_expand: 2
      ffn_expand: 2
      kernel_size: 1

training:
  iterations: 3200
  valid_interval: 64
  batch_size: 16

  optimizer:
    type: AdamW
    weight_decay: 0.0
    lr: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingLR
    t_max: 3200
    eta_min: !!float 1e-6

  losses:
    # mseloss:
    #   weight: 1.0
    l1loss:
      weight: 1.0

datasets:
  training:
    data_path: ~/Downloads/DIV2K_train_HR/
    
  validation:  
    data_path: ~/Downloads/DIV2K_valid_HR/

  patch_size: 128
  workers: 6


