
name: DSRNAFNet_V8

model:
  load_path: ./pretrained_models/DSRNAFNet_V4.pth
  ignore_yaml: True
  save_path: ./pretrained_models/
  device: 'cuda'

  network_arch:
    type: SRNAFNet
    width: 64
    enc_blk_nums: []
    mid_blk_num: 1
    dec_blk_nums: []

    intro_k: 3
    ending_k: 3

    sfe_k_nums: [3, 5, 7]
    dfe_count: 3
    dfe_k: 3
    ufe_count: 3
    ufe_k: 3

    block:
      dw_expand: 2
      ffn_expand: 2
      kernel_size: 1

training:
  iterations: 10000
  valid_interval: 64
  batch_size: 16

  optimizer:
    type: AdamW
    weight_decay: 0.0
    lr: !!float 1e-5
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingLR
    t_max: 10000 
    eta_min: !!float 1e-7

  losses:
    l1loss:
      weight: 1.0
    # vggloss:
    #   weight: 0.01

datasets:
  training:
    data_path: ~/Downloads/DF2K/
    
  validation:  
    data_path: ~/Downloads/DIV2K_valid_HR/

  patch_size: 128
  scale: 2
  workers: 6

