
name: NAFNet_k935_u1

model:
  # load_path: ./
  save_path: ./pretrained_models/
  device: 'cuda'

  network_arch:
    type: NAFNet
    width: 16
    enc_blk_nums: []
    mid_blk_num: 1
    dec_blk_nums: []

    intro_k: 9
    ending_k: 5

    block:
      dw_expand: 1
      ffn_expand: 4
      kernel_size: 3

training:
  iterations: 1600
  valid_interval: 100
  batch_size: 32

  optimizer:
    type: AdamW
    weight_decay: 0.0
    lr: !!float 1e-4
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingLR
    t_max: 1600
    eta_min: !!float 1e-7

  losses:
    psnrloss:
      weights: 1.0

datasets:
  training:
    data_path: ~/Downloads/DIV2K_train_HR/
    
  validation:  
    data_path: ~/Downloads/DIV2K_valid_HR/

  patch_size: 256
  workers: 6


