
name: NAFNet_w16_u111

model:
  # load_path: ./
  save_path: ./pretrained_models/
  device: 'cuda'

  network_arch:
    type: NAFNet
    width: 16
    enc_blk_nums: [1]
    mid_blk_num: 1
    dec_blk_nums: [1]

training:
  iterations: 1600
  valid_interval: 25
  batch_size: 64

  optimizer:
    type: AdamW
    weight_decay: 0.0
    lr: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: CosineAnnealingLR
    t_max: 1600
    eta_min: !!float 1e-7

  losses:
    psnrloss:
      weights: 1.0

datasets:
  training:
    data_path: ~/Downloads/DIV2K_train_HR/
    
  validation:  
    data_path: ~/Downloads/DIV2K_valid_HR/

  patch_size: 256
  workers: 6


